export default values = {
  LIKED_IMAGES: "LIKED_IMAGES",
  DIRECTORY_PATH: "DIRECTORY_PATH",
  RECENT_SEARCHES: "RECENT_SEARCHES",
  COLLECTIONS: "COLLECTIONS",
  COLLECTION_NAMES: "COLLECTION_NAMES",
  COLLECTIONS_PATH: "COLLECTIONS_PATH",
  DOWNLOADS_PATH: "DOWNLOADS_PATH",
  LOCAL_DOWNLOADS_PATH: "LOCAL_DOWNLOADS_PATH",
  TAGS: "TAGS",
  CATEGORIES: "CATEGORIES",
  LOCAL_FOLDERS: "LOCAL_FOLDERS",
};
