export default values = {
  LIKED_IMAGES: "LIKED_IMAGES",
  DIRECTORY_PATH: "DIRECTORY_PATH",
  RECENT_SEARCHES: "RECENT_SEARCHES",
  COLLECTIONS: "COLLECTIONS",
  COLLECTION_NAMES: "COLLECTION_NAMES",
};
